### ISSUE TITLE
Crash when using ReactiveCocoa 2

### ISSUE THREAD

**Issue by IanLuo** [bugtags/Bugtags-iOS#1]
If rac_signalForControlEvents is subscribed, when the action fires, app will crash

**\* -[RACDynamicSignal retain]: message sent to deallocated instance 0x7fa83572a700
#0  0x0000000114ca141f in **_forwarding**_ ()
#1  0x0000000114ca1098 in **forwarding_prep_0_** ()
#2  0x000000010fda21c1 in -[NSObject(BTGHelper) getVariableName:] at /Users/kaixin/Documents/Work/Bugtags/Code/Bugtags-iOS/Bugtags/Bugtags/Categories/NSObject+BTGHelper.m:37
#3  0x000000010fd9553f in -[UIApplication(BTGMethodSwizzler) swizzleSendAction:to:from:forEvent:] at /Users/kaixin/Documents/Work/Bugtags/Code/Bugtags-iOS/Bugtags/Bugtags/Categories/UIApplication+BTGMethodSwizzler.m:117
#4  0x00000001123e3bd9 in -[UIApplication sendAction:toTarget:fromSender:forEvent:]()
#5  0x000000011253f82c in -[UIControl sendAction:to:forEvent:]()
#6  0x000000011253fad2 in -[UIControl _sendActionsForEvents:withEvent:]()
#7  0x000000011253ecb7 in -[UIControl touchesEnded:withEvent:]()
#8  0x000000011286f062 in _UIGestureRecognizerUpdate ()
#9  0x000000011244a75c in -[UIWindow _sendGesturesForEvent:]()
#10 0x000000011244b84b in -[UIWindow sendEvent:]()
#11 0x00000001123ffff6 in -[UIApplication sendEvent:]()
#12 0x000000010fd94bde in -[UIApplication(BTGMethodSwizzler) swizzleSendEvent:] at /Users/kaixin/Documents/Work/Bugtags/Code/Bugtags-iOS/Bugtags/Bugtags/Categories/UIApplication+BTGMethodSwizzler.m:27
#13 0x00000001123dd093 in _UIApplicationHandleEventQueue ()
#14 0x0000000114c76781 in **CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** ()
#15 0x0000000114c6c58c in __CFRunLoopDoSources0 ()
#16 0x0000000114c6ba43 in __CFRunLoopRun ()
#17 0x0000000114c6b458 in CFRunLoopRunSpecific ()
#18 0x0000000117274bca in GSEventRunModal ()
#19 0x00000001123e21c2 in UIApplicationMain ()

**Comment by stephenzl** [comment]
We have fixed this issue, we are going to have a new version this afternoon, about two hours later, please update then. thx.

**Comment by stephenzl** [comment]
have fixed at 1.0.7, please update.
