### ISSUE TITLE
Xcode 升级到7 之后pod 报黄色警告

### ISSUE THREAD

**Issue by xcuYao** [bugtags/Bugtags-iOS#2]
![image](https://cloud.githubusercontent.com/assets/7591385/9984907/e9f0ef86-6053-11e5-93df-227cd73054e2.png)

这是我的Other Linker Flags 配置 应该是加了 -ObjC 参数的
![image](https://cloud.githubusercontent.com/assets/7591385/9984930/4b07e612-6054-11e5-9fff-b34599929874.png)

**Comment by stephenzl** [comment]
你好，请参考：http://help.bugtags.com/hc/kb/article/83193/

**Comment by xcuYao** [comment]
hi 我的解决方法 不太一样 
Xcode7 之后 设置
Build Settings -> Build Options->Debug Information Format 将DWARF with dSYM File 改为DWARF
警告就消除了
